
create sequence test1_seq start with 1
increment by 1;


CREATE TABLE test1 ( 
  FIELD1   VARCHAR2 (10)  NOT NULL, 
  FIELD2   VARCHAR2 (10)  NOT NULL, 
  FIELD3   VARCHAR2 (10)  NOT NULL, 
  NUM1     NUMBER        NOT NULL, 
  NUM2     NUMBER, 
  DATE1    DATE, 
  CONSTRAINT test1_PK
  PRIMARY KEY ( NUM1 ) 
    USING INDEX 
     TABLESPACE USERS PCTFREE 10 ) 
 TABLESPACE USERS
   PCTFREE 10   PCTUSED 40
   INITRANS 1   MAXTRANS 255
 STORAGE ( 
   INITIAL 4k NEXT 4k PCTINCREASE 0
   MINEXTENTS 1 MAXEXTENTS 4096 )
   NOCACHE; 


CREATE TABLE test2 ( 
  FIELD1   VARCHAR2 (10)  NOT NULL, 
  FIELD2   VARCHAR2 (10)  NOT NULL, 
  FIELD3   VARCHAR2 (10)  NOT NULL, 
  NUM1     NUMBER        NOT NULL, 
  NUM2     NUMBER, 
  DATE1    DATE, 
  commit_time  date,
  op_type varchar2(10),
  CONSTRAINT test2_PK
  PRIMARY KEY ( NUM1 ) 
    USING INDEX 
     TABLESPACE USERS PCTFREE 10 ) 
 TABLESPACE USERS
   PCTFREE 10   PCTUSED 40
   INITRANS 1   MAXTRANS 255
 STORAGE ( 
   INITIAL 4k NEXT 4k PCTINCREASE 0
   MINEXTENTS 1 MAXEXTENTS 4096 )
   NOCACHE; 


CREATE TABLE testdef ( 
  FIELD1   VARCHAR2 (10)  NOT NULL, 
  FIELD2   VARCHAR2 (10)  NOT NULL, 
  FIELD3   VARCHAR2 (10)  NOT NULL, 
  NUM1     NUMBER        NOT NULL, 
  NUM2     NUMBER, 
  DATE1    DATE, 
  commit_time  date,
  op_type varchar2(10));
